{
	"version": 1643120662,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/sprite2-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/u-sheet0.png",
		"images/tiledbackground2.png",
		"images/sprite16-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/tiledbackground4.png",
		"images/sprite19-sheet0.png",
		"images/sprite20-sheet0.png",
		"images/орпап-sheet0.png",
		"images/орпап2-sheet0.png",
		"images/sprite21-sheet0.png",
		"images/sprite22-sheet0.png",
		"images/sprite30-sheet0.png",
		"images/sprite33-sheet0.png",
		"images/sprite34-sheet0.png",
		"images/sprite35-sheet0.png",
		"media/machine-gun-vickers-four-shots-close-perspective_zj1e5ne_ (mp3cut.net).m4a",
		"media/machine-gun-vickers-four-shots-close-perspective_zj1e5ne_ (mp3cut.net).ogg",
		"media/30e76264d79c3d9 (mp3cut.net).m4a",
		"media/30e76264d79c3d9 (mp3cut.net).ogg",
		"media/03968 (mp3cut.net).m4a",
		"media/03968 (mp3cut.net).ogg",
		"media/jan 03, 02.48 pm_Голос мальчика(1) (mp3cut.net).m4a",
		"media/jan 03, 02.48 pm_Голос мальчика(1) (mp3cut.net).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"c2mp-net.js",
		"c2mp-peer.js",
		"c2mp.js",
		"waker.js"
	]
}